[tool.poetry]
name = "avo-events-archived"
version = "0.1.0"
description = ""
authors = ["rudolf <rudolf.degeijter@meemoo.be>"]

[tool.poetry.dependencies]
python = "^3.8"
uWSGI = "^2.0.19"
Flask = "^1.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
