apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "web-app"
  name: "avo-events-archived"
  labels:
    app: "avo-events-archived"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "avo-events-archived-${env}"
      namespace: "avo"
      labels:
        app: "avo-events-archived"
        app.kubernetes.io/component: "avo-events-archived-${env}"
        app.kubernetes.io/instance: "avo-events-archived-${env}"
        app.kubernetes.io/name: "avo-events-archived"
        app.kubernetes.io/part-of: "avo-events-archived"
        app.openshift.io/runtime: "avo-events-archived"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "avo-events-archived-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      name: "avo-events-archived-${env}"
      namespace: "avo"
      labels:
        app: "avo-events-archived"
        app.kubernetes.io/component: "avo-events-archived-${env}"
        app.kubernetes.io/instance: "avo-events-archived-${env}"
        app.kubernetes.io/name: "avo-events-archived"
        app.kubernetes.io/part-of: "avo-events-archived"
        app.openshift.io/runtime: "avo-events-archived"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "avo-events-archived-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "avo-events-archived-${env}"
            deploymentconfig: "avo-events-archived-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "avo-events-archived-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: "${cpu_limit}m"
                  memory: "${memory_limit}Mi"
                requests:
                  cpu: "${cpu_requested}m"
                  memory: "${memory_requested}Mi"
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: ${{svc_port}}
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              readinessProbe:
                tcpSocket:
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "avo-events-archived-${env}"
                - secretRef:
                    name: "avo-events-archived-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/avo/avo-events-archived:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "avo-events-archived-${env}"
      namespace: "avo"
      labels:
        app: "avo-events-archived"
        app.kubernetes.io/component: "avo-events-archived-${env}"
        app.kubernetes.io/instance: "avo-events-archived-${env}"
        app.kubernetes.io/name: "avo-events-archived"
        app.kubernetes.io/part-of: "avo-events-archived"
        app.openshift.io/runtime: "avo-events-archived"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      APP_ENVIRONMENT: some_value
      MEDIAHAVEN_HOST: some_value
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "avo-events-archived-${env}"
      namespace: "avo"
      labels:
        app: "avo-events-archived"
        app.kubernetes.io/component: "avo-events-archived-${env}"
        app.kubernetes.io/instance: "avo-events-archived-${env}"
        app.kubernetes.io/name: "avo-events-archived"
        app.kubernetes.io/part-of: "avo-events-archived"
        app.openshift.io/runtime: "avo-events-archived"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    stringData:
      MEDIAHAVEN_USERNAME: ""
      MEDIAHAVEN_PASSWORD: ""
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"
